### ISSUE TITLE
error running the script

### ISSUE THREAD

**Issue by baditaflorin** [mapbox/csv2geojson#56]
csv2geojson osmose-planet-latest.csv > osmose_geodata.geojson
buffer.js:11
    super(arg1, arg2, arg3);
    ^

RangeError: Invalid typed array length
    at Buffer.Uint8Array (native)
    at FastBuffer (buffer.js:11:5)
    at createUnsafeBuffer (buffer.js:38:12)
    at allocate (buffer.js:181:12)
    at Function.Buffer.allocUnsafe (buffer.js:141:10)
    at Function.Buffer.concat (buffer.js:309:23)
    at bufferConcat (/usr/lib/node_modules/csv2geojson/node_modules/concat-stream/index.js:116:17)
    at ConcatStream.getBody (/usr/lib/node_modules/csv2geojson/node_modules/concat-stream/index.js:63:42)
    at ConcatStream.<anonymous> (/usr/lib/node_modules/csv2geojson/node_modules/concat-stream/index.js:36:51)
    at emitNone (events.js:91:20)

**Comment by andrewharvey** [comment]
Could you post the contents of `osmose-planet-latest.csv` please?
